version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-wacdo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: motdepasse
      MYSQL_DATABASE: wacdo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: motdepasse
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
